name: Malene
channels:
  - conda-forge
dependencies:
    - python == 3.6
    - numpy == 1.12
    - scipy == 1.4.1
    - matplotlib == 2.1
    - scikit-image == 0.16
    - notebook == 4.0
    - jupyter_client == 5.1.0
    - pandas == 1.0.3
    - scikit-image == 0.16
    - pip:
        - czifile
        - glob2
